### ISSUE TITLE
bug: TikTok Memory

### ISSUE THREAD

**Issue by ripnonfegames** [revanced/revanced-patches#1358]
### Type

Error while patching

### Bug description

I was patching TikTok and it said aborting due to memory error.

### Steps to reproduce

1. Patch TikTok with 5 selected patches.
Disable Login Requirement
Downloads
Hide Ads
Show seekbar and SIM spoof 

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Applied downloads
Applied hide-ads
Applied settings
Applied show-seekbar
Applied sim-spoof
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 60476232 byte allocation with 65264 free bytes and 63KB until OOM, target footprint 536870912, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3161)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:179)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Starmania** [comment]
Does your phone is a potato ?

**Comment by ripnonfegames** [comment]
> Does your phone is a potato ?

I have 12GB of ram, so no.

**Comment by ripnonfegames** [comment]
> #1248

I saw that but there's no clear answer.

**Comment by Starmania** [comment]
If you really have 12GB of RAM, try patch older one (and send the first older version that work for anyone having the same problem)

**Comment by shaiws** [comment]
Facing the same. Though I have 8 gigs plus 6 gigs of Samsung "ram plus".
`Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Applied hide-ads
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 75918768 byte allocation with 1654840 free bytes and 1616KB until OOM, target footprint 536870912, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3670)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)`

**Comment by ghaschel** [comment]
Same happens to me. S22 ultra, 12gb ram + 4gb Ram Plus.

This happens on tiktok and twitter

**Comment by xscd** [comment]
![photo_2023-01-15_19-29-13](https://user-images.githubusercontent.com/46658470/212553374-4708667e-f2d4-4ffe-8839-40e71248ef05.jpg)

This hasn't been fixed even with the latest repatcher update. can it be re-opened?

**Comment by oSumAtrIX** [comment]
There is no release yet. It has been fixed in upstream.

**Comment by geiszla** [comment]
Is it still not released? I'm still having problems on the latest version (with the latest TikTok apk).

**Comment by ripnonfegames** [comment]
Why was this set as completed? I'm still having the problem

**Comment by oSumAtrIX** [comment]
The issue was closed because it was solved. Open a new issue if you experience it

**Comment by ripnonfegames** [comment]
but it's my ticket

**Comment by oSumAtrIX** [comment]
Yes, but it is outdated, open a new one with the updated info

**Comment by VishramKidPG123** [comment]
> Same happens to me. S22 ultra, 12gb ram + 4gb Ram Plus.
> 
> This happens on tiktok and twitter 

Yeah, I'm still getting this error, don't know why it's closed since there's no solution. I am also using an S22 Ultra, with 12gb RAM and 8gb RAM Plus, and I'm getting this error with TikTok. 

Here are my logs: 
```
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborted
Error:
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 4385696 free bytes and 4282KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3766)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
	at java.lang.StringBuilder.append(StringBuilder.java:137)
	at brut.androlib.res.decoder.ARSCDecoder.addMissingResSpecs(ARSCDecoder.java:553)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:233)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:132)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:778)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:66)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:58)
	at brut.androlib.Androlib.getResTable(Androlib.java:74)
	at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:204)
	at app.revanced.patcher.Patcher.access$decodeResources(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:351)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012
```)
