### ISSUE TITLE
bug: back button/gesture not working as intended

### ISSUE THREAD

**Issue by Cypher-Emm** [revanced/revanced-patches#1365]
### Type

Other

### Bug description

The back button/gesture doesn't exit app.
Using rooted yt patched with latest patches(not dev), integrations and cli.
Back gesture works for exiting app only if i don't change any settings either youtube's settings or rv settings/sponsorblock.
The predictive back gesture pack is excluded by default but i suspect this bug appeared after introduction of predictive back gesture patch.
Device : Samsung Galaxy A10 (arm)
Android 11 rooted stock one ui 3.1

### Steps to reproduce

Patch yt with cli using latest patches, cli and integrations(not dev builds)
After patching launch yt and test back key for exiting app. It will work . Now change some settings and the app won't exit with back gesture

### Relevant log output

```shell
...
```

### Solution

...

### Additional context

Can anyone else reproduce this or is it only me

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#632

**Comment by oSumAtrIX** [comment]
#vack

**Comment by Domiiniik** [comment]
Lmao 🤣🤣 this is false dude, the patches that are excluded take no effect on your app dude, besides this bug is really old and exists since quite some time before back gesture or android 13 even existed 🤣🤣

**Comment by 0xrxL** [comment]
This should fix the timeframe during which the back button does not work:

https://github.com/revanced/revanced-patches/pull/1369

**Comment by oSumAtrIX** [comment]
> This should prevent the situation during which the back button does not work:
> 
> #1369

The back gesture remains non-functional. Instead, it adds a workaround whereas a faster and already existing workaround exists.

**Comment by 0xrxL** [comment]
> > This should prevent the situation during which the back button does not work:
> > #1369
> 
> The back gesture remains non-functional. Instead, it adds a workaround whereas a faster and already existing workaround exists.

Unfortunately there's no known way to restore the original back to exit feature. So this workaround should be good enough, because it's exactly the same of the stock one.

**Comment by oSumAtrIX** [comment]
The PR which was opened required swiping back twice.

**Comment by 0xrxL** [comment]
> The PR which was opened required swiping back twice.

The code of PR however can be adapted to all amount of swipes, also 1.

**Comment by oSumAtrIX** [comment]
In that case please adapt that.

**Comment by 0xrxL** [comment]
> In that case please adapt that.

@inotia00

**Comment by Sunny-Shani** [comment]
Same issue dude back button is not working :(

**Comment by 0xrxL** [comment]
@oSumAtrIX This should be fixed now with last merged PR.

**Comment by Cypher-Emm** [comment]
Yup it is working properly now.

**Comment by oSumAtrIX** [comment]
> @oSumAtrIX This should be fixed now with last merged PR.

Please link the PR.

**Comment by 0xrxL** [comment]
> > @oSumAtrIX This should be fixed now with last merged PR.
> 
> Please link the PR.

https://github.com/revanced/revanced-patches/commit/24405877dd935a757fa61c7580887c1a47a25ea9

**Comment by Sunny-Shani** [comment]
> > > @oSumAtrIX This should be fixed now with last merged PR.
> > 
> > 
> > Please link the PR.
> 
> [2440587](https://github.com/revanced/revanced-patches/commit/24405877dd935a757fa61c7580887c1a47a25ea9)

Can you tell me what is PR? Do I have to install any patches? Because mine back button still not working I am new here on github I don't know how things work.

**Comment by oSumAtrIX** [comment]
The PR has been abandoned by the author.

**Comment by Sunny-Shani** [comment]
> The PR has been abandoned by the author.

It means that issue with back button still exists and I have to wait for it be fixed?

**Comment by Indranil012** [comment]
the issue is fixed. why is it still opened?

**Comment by Sunny-Shani** [comment]
> the issue is fixed. why is it still opened?

Not fixed dude my still not working

**Comment by Indranil012** [comment]
> Not fixed dude mine still not working

strange

**Comment by Sunny-Shani** [comment]
> > Not fixed dude mine still not working
> 
> strange

Your back button is working properly?

**Comment by Indranil012** [comment]
> Your back button is working properly?

yes, absolutely
