### ISSUE TITLE
bug: <YouTube videos loading forever after a bit of normal playback>

### ISSUE THREAD

**Issue by MissingNerd** [revanced/revanced-patches#1834]
### Type

Error at runtime

### Bug description

This started yesterday after weeks without issues. Whenever I watch a video without downloading it first it will eventually enter a infinite loading screen and stop playing. Doesn't seem to relate to connection. 
Things I've tried: clearing cache, force stop, repatch the whole thing, switch to a newer YouTube version
My phone:
Fairphone 4 running Android 12
My app:
v18.05.40
Selected patches (19)
Client Spoof (v0.0.1)
Copy Video Url (v0.0.1)
Custom Branding (v0.0.1)
Disable Auto Captions (v0.0.1)
Disable Shorts On Startup (v0.0.1)
Downloads (v0.0.1)
Enable Wide Searchbar (v0.0.1)
Hide Create Button (v0.0.1)
Hide Crowdfunding Box (v0.0.1)
Hide My Mix (v0.0.1)
Hide Shorts Button (v0.0.1)
Hide Watermark (v0.0.1)
MicroG Support (v0.0.1)
Old Quality Layout (v0.0.1)
Open Links Externally (v0.0.1)
Remember Video Quality (v0.0.1)
Remove Screenshot Restriction (v0.0.1)
Return Youtube Dislike (v0.0.1)
Sponsorblock (v0.0.1)

### Steps to reproduce

1. Watch a video
2. Wait

### Relevant log output

```shell
No crashes and no idea how to create logs otherwise
```

### Screenshots or videos

![IMG_20230401_121627_815](https://user-images.githubusercontent.com/45050738/229280254-5b13541a-f134-42b5-a282-f702a6aed9a3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Include the recommended/default set of patches, it includes the patch which should solve this issue.

**Comment by MissingNerd** [comment]
The only thing that adds to my patch set is debugging options. How does
that solve anything?

**Comment by MissingNerd** [comment]
I think you meant I need client spoof but I already have that

**Comment by Ushie** [comment]
You need Spoof Signature Verification

**Comment by MissingNerd** [comment]
Ok, my bad. It still doesn't work after that tho. I've also seen 2 more
people with the same problem just today on telegram

**Comment by oSumAtrIX** [comment]
You are out of luck
