### ISSUE TITLE
bug: (YT Music) Upgrade patch doesn't work in `6.15.51`

### ISSUE THREAD

**Issue by shivanshvermak** [ReVanced/revanced-patches#2838]
### Type

Cosmetic

### Bug description

Hi, I updated the YT Music app today and Upgrade button doesn't hide after patching. It however doesn't display any issue while patching in the manager. 

Additionally, there's a new "Samples" option. 
![Screenshot_20230818-071558](https://github.com/ReVanced/revanced-patches/assets/15206857/a75dd36b-23bc-4e24-9759-34ee449e0c99)

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by YT-Advanced** [comment]
Youtube changed in their server side, they added new tab named Samples so that is why YT Music hide Library tab instead of Upgrade tab

**Comment by oSumAtrIX** [comment]
Changing this index should fix the issue:
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/1979575b-5c00-427c-a0c9-04bab569e1df)

A better approach to this rather naive one would be to get the length of the list and hide the last.

**Comment by YT-Advanced** [comment]
> A better approach to this rather naive one would be to get the length of the list and hide the last.

Right, since it is an A/B Testing, I think get the length is better at all

**Comment by kazimmt** [comment]
> A better approach to this rather naive one would be to get the length of the list and hide the last.

Agree, otherwise people who don't under current A/B test will see a upgrade button even they select the Remove Upgrade button patch.
Like this: 
![photo_2023-08-19_11-10-00](https://github.com/ReVanced/revanced-patches/assets/82371061/c769a861-b049-4895-a2ac-7fc6e6f51e2d)
Remove upgrade button is selected but still showing Upgrade button (dev patches)
