### ISSUE TITLE
Ads on Home Page

### ISSUE THREAD

**Issue by mjain234** [revanced/revanced-patches#520]
### Type

Other

### Bug description

Recently after patching and installing Revanced through Revanced manager as a ROOT varient, i can still see some ads appearing in home page of the app  i tried uninstalling  and installing it again, but still ads showing.

### Steps to reproduce

Step 1. Downloaded latest Revanced Manager v.0.0.7

Step 2. Selected Youtube v.17.33.42

Step 3. Edited patch option by deselecting 
             • MicroG support (as my device is rooted)
             • Hide Autobrigtness
             • Hide Autoplay button
             • Hide Cast button
             • Hide Shorts button

### Relevant log output

```shell
NIL
```

### Screenshots or videos

https://user-images.githubusercontent.com/70900505/190867942-edec8bca-ad99-4211-a28d-8cd262386e60.mp4

### Additional context

Device Name - Realme 2 Pro

Android version - Android 13

ROM - Arrow OS

**Comment by oSumAtrIX** [comment]
Pleasenfollow the official documentation and use the latest integrations, this issue was recently fixed.

**Comment by mjain234** [comment]
So, i look upon Revanced Integrations and found an apk named "app_release unsigned apk" and when I installed it, showed me this [error](![Screenshot_20220917-230349.png](https://user-images.githubusercontent.com/70900505/190871438-6c0a5149-013a-469a-9080-de7fdbb14ac6.png))

**Comment by oSumAtrIX** [comment]
Please follow the documentation, you are not supposed to install that anywhere in the docs.

**Comment by mjain234** [comment]
Can you guide me to the official documentation? I searched everywhere but cannot find the documentation you are talking about😐

**Comment by johnconner122** [comment]
this is official documentation:
https://github.com/revanced/revanced-documentation

**Comment by mjain234** [comment]
> this is official documentation:
> https://github.com/revanced/revanced-documentation

I have a small doubt, like whenever there is a update for Revanced Manager, so at the same time i have to update YouTube and it's Patches too?

**Comment by Aunali321** [comment]
No need. Manager updates are separate from other updates.

**Comment by mjain234** [comment]
> No need. Manager updates are separate from other updates.

But my issue here is that Revanced is still showing ads and i came to know "it has been fixed in latest integration", what should I do about that? Is there something i have to do?

**Comment by Aunali321** [comment]
Manager automatically uses latest patches and integrations. You can try uninstalling and reinstalling.

**Comment by mjain234** [comment]
> Manager automatically uses latest patches and integrations. You can try uninstalling and reinstalling.

So, manager don't update the youtube app itself , i have to manually download youtube recommended version from site and then use manager to patch it? Is that Revanced works? Actually i dont know how this works, that's why asking such question, please don't mind😅

**Comment by Aunali321** [comment]
Yes, that allows user to use any version of youtube app instead of just latest. its a feature not a bug.

**Comment by dimon222** [comment]
I have the same issue even with latest versions of revanced manager/new rebuilt apk by revanced buiolder. It seems to be device specific since I used the same patched APK on two devices and one device was fine, but another still showed ads on home screen & underneath the video while playing (first video below is an ad).

Device 1 - shows ads - tablet Samsung SM-T720 (Android 12)
Device 2 - no ads - phone Poco X4 Pro (Android 12L)

It could be tablet using some another layout that wasn't affected by patcher somehow, but I'm not certain.

**Comment by mjain234** [comment]
> I have the same issue even with latest versions of revanced manager/new rebuilt apk by revanced buiolder. It seems to be device specific since I used the same patched APK on two devices and one device was fine, but another still showed ads on home screen & underneath the video while playing (first video below is an ad).
> 
> Device 1 - shows ads - tablet Samsung SM-T720 (Lineage OS - Android 12)
> Device 2 - no ads - phone Poco X4 Pro (Pixel Experience - Android 12L)
> 
> It could be tablet using some another layout that wasn't affected by patcher somehow, but I'm not certain.
> The old Youtube Vanced isn't showing ads.

I think there may be issue between root version and non root version, because in two of my other phones which is a non root version, there ain't showing any ads with revanced manager but in my phone which is a root version, showing ads on only home page and ads below the video.

**Comment by dimon222** [comment]
> > I have the same issue even with latest versions of revanced manager/new rebuilt apk by revanced buiolder. It seems to be device specific since I used the same patched APK on two devices and one device was fine, but another still showed ads on home screen & underneath the video while playing (first video below is an ad).
> > Device 1 - shows ads - tablet Samsung SM-T720 (Lineage OS - Android 12)
> > Device 2 - no ads - phone Poco X4 Pro (Pixel Experience - Android 12L)
> > It could be tablet using some another layout that wasn't affected by patcher somehow, but I'm not certain.
> > The old Youtube Vanced isn't showing ads.
> 
> I think there may be issue between root version and non root version, because in two of my other phones which is a non root version, there ain't showing any ads with revanced manager but in my phone which is a root version, showing ads on only home page and ads below the video.

I used non-root version on both my devices, so thats definitely not related to that.

**Comment by mjain234** [comment]
Yes, that's the case, the non root version is not facing any ads as what i have seen and get to know from the people using non root but root version gettings ads

**Comment by worstperson** [comment]
IP seems to have an effect. I'm getting these ads when using Cloudflare Warp(from Texas), but they disappear when I connect through a Google Cloud server in Oregon.

**Comment by antakor** [comment]
I have ads on my Samsung SM-P610 (Android 12 Stock - non root)

**Comment by johnconner122** [comment]
I've logged in two accounts in microg. I see ads on one account and don't see on other account.

**Comment by jagtarsidhu** [comment]
Yes Home page issue is only on rooted devices. am also facing it.

**Comment by l-Nuril-l** [comment]
> Yes Home ads issue is only on rooted devices. am also facing it.

Not only rooted

**Comment by Methos90** [comment]
So it seems that the patch does block home ads like it should but only when i'm not signed into my account. As soon as i sign in i start getting home ads. So i would assume the problem has to do with being logged in which is weird to say the least.

I'm using a Galaxy S10 with Android 12. I patched Youtube 17.36.37 with Revanced Manager 0.0.24. I included all patches except debug.

**Comment by Methos90** [comment]
Okay so i decided to reinstall everything again including vanced microg and before i logged back in it still showed a home ad. Incognito mode still shows zero ads.
![Screenshot_20220924-202223](https://user-images.githubusercontent.com/114308132/192113309-dd1af58e-3e7b-4a97-bbf7-8f07e58b6ff1.png)

**Comment by laurencesmithever** [comment]
Same issue here.

**Comment by jjohnstondev** [comment]
On a fold 4 I get home screen ads consistently

**Comment by meichengg** [comment]
Is this issue being working on? I see there is no new update on `ads` patches.

**Comment by dimon222** [comment]
Seems fixed now.
https://github.com/revanced/revanced-patches/commit/fd0506eb95dbf398eb7d6bfa8732f517b9867545
Verified, indeed solved.

Small thing - successfully ad-blocked suggested videos showed as empty black area (perhaps video blocks don't get reordered when patch kicks in). Perhaps going to be sorted in future improvements.

**Comment by oSumAtrIX** [comment]
Can you add a picture @dimon222?

**Comment by dimon222** [comment]
![image](https://user-images.githubusercontent.com/2671025/193499677-02a7a4a6-416d-48cf-8e9d-91cec9e7eadf.png)

**Comment by antakor** [comment]
I have the same black square under the video-player in vertical tablet mode so those ads are now blocked.

Sadly I still have ads on the homescreen.

![Screenshot_20221003-150200](https://user-images.githubusercontent.com/85926470/193586281-a46357fb-a129-494d-8fff-2a0f169129c3.jpg)

**Comment by mjain234** [comment]
I think the ads are not showing for now which is great!
