### ISSUE TITLE
bug: yt music - error 400

### ISSUE THREAD

**Issue by ymyogev** [ReVanced/revanced-patches#5718]
### Bug description

Sometime this morning yt music has stopped functioning. 
Tried reinstall after patching with a few different versions but to no avail. 
When switching Google accounts some work, but not my main one. 
Any way to fix this? 

![Image](https://github.com/user-attachments/assets/ea2f6bf5-fa28-4634-8c29-afb388cc0994)

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by fbievan** [comment]
> > When switching Google accounts some work, but not my main one.
> 
> if that's the case, does it also not work on the official yt music / youtube app and the site version of youtube (music)?

I was also trying, it started yesterday for me. For me same thing happening with the revance patched version, however unpatched ytmusic works normally

**Comment by jpa102** [comment]
how about trying to patch yt music with older patches version with [revanced-cli?](https://github.com/ReVanced/revanced-cli)

**Comment by jpa102** [comment]
i tried patching `8.34.51` with revanced-cli and it also has no issues for me (action buttons still broken as usual)

![Screenshot_20250827_201811_YouTube Music.png](https://github.com/user-attachments/assets/791acc85-4098-48db-9258-75e0b18610a8)

not sure what's going on, but i'll stick with your a/b test claim (other users speculated it's also an account issue)

**Comment by mbalax** [comment]
I'm having the same issue, have tried re-installing, patching, clearing cache, updating MicroG all as recommended, no soap. Hope someone can find a fix!

**Comment by jpa102** [comment]
@ymyogev i'm sorry but even if i want to, my limited mobile data plan will not help

there are tutorials on reddit though

**Comment by jask77** [comment]
I have the same issue with 8.34.51 and 8.33.53. It was working fine for weeks until now.

![Image](https://github.com/user-attachments/assets/5300580a-ee51-4be5-aa9e-7742a3e6ba8f)

**Comment by rbnhd** [comment]
I have this issue on `8.33.54` patched.
Has anyone found a solution?

**Comment by jpa102** [comment]
anyone that confirmed it's not their youtube account having hiccups both on revanced and stock versions (even the website version), can try patching with revanced-cli until this issue is addressed

this will use an older patches and yt music version: (pc is needed here)

    java -jar revanced-cli-5.0.1.jar patch youtubemusic-7.29.52-arm64-v8a.apk -p patches-5.4.0.rvp

or a slightly older patches version:

    java -jar revanced-cli-5.0.1.jar patch youtubemusic-8.05.51-arm64-v8a.apk -p patches-5.27.0.rvp

* [revanced cli 5.0.1](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.1)
* [patches 5.4.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.4.0)
* [patches 5.27.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.27.0)

***

there is no guarantee that this method may help anyone, as cyberboh pointed out that the `Spoof client` patch may need some updating

**Comment by rbnhd** [comment]
> anyone that confirmed it's not their youtube account having hiccups both on revanced and stock versions (even the website version), can try patching with revanced-cli until this issue is addressed
> 
> this will use an older patches and yt music version: (pc is needed here)
> 
> ```
> java -jar revanced-cli-5.0.1.jar patch youtubemusic-7.29.52-arm64-v8a.apk -p patches-5.4.0.rvp
> ```
> 
> or a slightly older patches version:
> 
> ```
> java -jar revanced-cli-5.0.1.jar patch youtubemusic-8.05.51-arm64-v8a.apk -p patches-5.27.0.rvp
> ```
> 
> * [revanced cli 5.0.1](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.1)
> * [patches 5.4.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.4.0)
> * [patches 5.27.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.27.0)
> 
> there is no guarantee that this method may help anyone, as cyberboh pointed out that the `Spoof client` patch may need some updating


Hey, tried this. The patched apk still gives the same error.

**Comment by jpa102** [comment]
you're welcome, glad it worked for you @rbnhd 

it also has opus codec if anyone cares

![Screenshot_20250828_131429_YouTube Music.png](https://github.com/user-attachments/assets/02cd7689-80c1-42c3-a770-7431b61feca9)

**Comment by Czajkor** [comment]
@jpa102 your patched version plays only first 60 seconds or so

**Comment by jpa102** [comment]
@Czajkor is it the one you just patched with revanced-cli right? (and no, i'm not giving out prepatched apks to anyone unless really necessary)

that's weird, as i can also see this similar error when turning off `Spoof video streams` in youtube revanced

**Comment by Czajkor** [comment]
> [@Czajkor](https://github.com/Czajkor) is it the one you just patched with revanced-cli right? (and no, i'm not giving out prepatched apks to anyone unless really necessary)
> 
> that's weird, as i can also see this similar error when turning off `Spoof video streams` in youtube revanced

No, I am on my phone right now, so I used your complied version

**Comment by Czajkor** [comment]
> [@Czajkor](https://github.com/Czajkor)
> 
> > No, I am on my phone right now, so I used your complied version. It buffers first minute right away and then it stops
> 
> Are u talking about the patched apk I provided in [this comment](https://github.com/ReVanced/revanced-patches/issues/5718#issuecomment-3231900869) ? I am using it and don't have this issue. (_Android 16_)

Yes, that's what I am talking about. I am glad it works on your side, just saying it doesn't on mine. A16 here too, if that matters

**Comment by brosssh** [comment]
> this will use an older patches and yt music version: (pc is needed here)
> 
>     java -jar revanced-cli-5.0.1.jar patch youtubemusic-7.29.52-arm64-v8a.apk -p patches-5.4.0.rvp
> 
> * [revanced cli 5.0.1](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.1)
> * [patches 5.4.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.4.0)
> ***
> 

So according to some feedback received in Discord, this workaround seems to be working. It's likely that yt music version doesn't have the code to handle the new experiment.

Please try this if you have problems and report the result.

**Comment by jpa102** [comment]
i think it's about time that it should have its own dedicated revanced settings for yt music, just like youtube

in the older `5.4.0` version, it seems to be [spoofing to `Android VR`](https://github.com/ReVanced/revanced-patches/blob/17a5a6c1691b0c23f601d3355b72f122c2bd5dcb/patches/src/main/kotlin/app/revanced/patches/music/misc/spoof/SpoofVideoStreamsPatch.kt) which only takes 1 file [compared to the current method (3 files)](https://github.com/ReVanced/revanced-patches/tree/main/patches/src/main/kotlin/app/revanced/patches/music/misc/spoof)

**Comment by ymyogev** [comment]
Can't compile for some reason.
Is it a JDK thing?
<img width="1919" height="645" alt="Image" src="https://github.com/user-attachments/assets/3cabc274-83ec-4797-bb60-42adc6c6734b" />

**Comment by jpa102** [comment]
that `terminally deprecated` warning can also be seen here: https://github.com/ReVanced/revanced-cli/issues/377

what jdk are you using? here's mine:

<img width="677" height="341" alt="Image" src="https://github.com/user-attachments/assets/f2130f5c-d1ee-462f-91bb-25b32441ec12" />

**Comment by rbnhd** [comment]
> that `terminally deprecated` warning can also be seen here: [ReVanced/revanced-cli#377](https://github.com/ReVanced/revanced-cli/issues/377)
> 
> what jdk are you using? here's mine:
> 
> <img alt="Image" width="677" height="341" src="https://private-user-images.githubusercontent.com/161832897/483009911-f2130f5c-d1ee-462f-91bb-25b32441ec12.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzNjY4MzYsIm5iZiI6MTc1NjM2NjUzNiwicGF0aCI6Ii8xNjE4MzI4OTcvNDgzMDA5OTExLWYyMTMwZjVjLWQxZWUtNDYyZi05MWJiLTI1YjMyNDQxZWMxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyOFQwNzM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzUzMmZjMDY4OWZhMzlhODcwYzlhMzU3N2Y0YmNmZGRhYjQwZWU2M2Q5MTI2NmEwYTU1N2Q2NzkzNzE4MWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q8Rmw2AeJspmo4h123ZcqWKiDhkBRVJMh-AjZ9Cy63Y">

@jpa102 
`Microsoft Windows [Version 6.0.6003]` って… 何年に生きてるんだよ（笑）！

**Comment by oSumAtrIX** [comment]
Use English

**Comment by ymyogev** [comment]
OK, version 7.29.52 works, really interesting.
Thank you @jpa102 !
What to do now, just use this version, or maybe it will be fixed in future updates?

**Comment by jpa102** [comment]
@ymyogev i'd say use this version of yt music with `5.4.0` patches version for now until this issue is resolved

i have been using this build for many months now and has never failed on me

***

>it will be fixed in future updates?

it will, give the devs some time

**Comment by Czajkor** [comment]
> > this will use an older patches and yt music version: (pc is needed here)
> > ```
> > java -jar revanced-cli-5.0.1.jar patch youtubemusic-7.29.52-arm64-v8a.apk -p patches-5.4.0.rvp
> > ```

> > * [revanced cli 5.0.1](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.1)
> > * [patches 5.4.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.4.0)
> 
> So according to some feedback received in Discord, this workaround by [@jpa102](https://github.com/jpa102) seems to be working. It's likely that yt music version doesn't have the code to handle the new experiment.
> 
> Please try this if you have problems and report the result.

java -jar revanced-cli-5.0.1-all.jar patch youtubemusic-7.29.54.apk -p patches-5.4.0.rvp

this is what worked for me, as I couldn't find 7.29.52, I got 7.29.54 from apkmirror

**Comment by imli700** [comment]
> Could you try login with your brother's account in your device? It seems more likely that the inconsistent errors are because of YouTube doing A/B tests with only some accounts having the breaking new feature. I personally have one of my accounts fail while the other works just fine in the same device

Ok yup his account doesn't work on my phone either. It's def an account issue

**Comment by r4h4du1r4f3** [comment]
> anyone that confirmed it's not their youtube account having hiccups both on revanced and stock versions (even the website version), can try patching with revanced-cli until this issue is addressed
> 
> this will use an older patches and yt music version: (pc is needed here)
> 
> ```
> java -jar revanced-cli-5.0.1.jar patch youtubemusic-7.29.52-arm64-v8a.apk -p patches-5.4.0.rvp
> ```
> 
> or a slightly older patches version:
> 
> ```
> java -jar revanced-cli-5.0.1.jar patch youtubemusic-8.05.51-arm64-v8a.apk -p patches-5.27.0.rvp
> ```
> 
> * [revanced cli 5.0.1](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.1)
> * [patches 5.4.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.4.0)
> * [patches 5.27.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.27.0)
> 
> there is no guarantee that this method may help anyone, as cyberboh pointed out that the `Spoof client` patch may need some updating

Thanks 1st method worked. None of the revanced or extended patches were working before

**Comment by brosssh** [comment]
Can anyone (that currently has the 400 issue) please test if using the patches v5.4.0 with the current suggested YT music works or get the 400 issue again? Basically I need to understand if it's related to the app version (aka the app version doesn't have the code to handle the flag) or if it's related to the patches itself (the old spoofing method still works).

(I'd do it myself but I don't have issues in any account)

**Comment by Czajkor** [comment]
Funny thing. After some time, it again stopped playing beyond first 60 seconds

**Comment by Czajkor** [comment]
@brosssh so, it again stopped playing beyond first 60 seconds. It will try to buffer, but it stops and song never plays, except when I am on video tab. In that case, I can buffer and swich back to song tab

**Comment by jask77** [comment]
I believe it is the patch issue, as I tried 7.29.52 with the latest default patches using the ReVanced Manager app. It returned the same error 400. I cannot comment on using CLI as it believes my APK does not exist.

![Image](https://github.com/user-attachments/assets/2e5b1d20-595f-4397-87a7-5af6184ee95d)

![Image](https://github.com/user-attachments/assets/498bad46-0f55-40d6-8f00-67cb6dad7a5c)

**Comment by AbusiveOatmeal** [comment]
Also had the error 400 tied to my primary yt account since 26Aug. On Windows 11, I used revanced-cli and the commands below to generate new patched apks for v7.16.53, v7.25.53, and  v7.29.52 using patch v5.4.0. (just to test different versions)

`java -jar .\revanced-cli.jar patch '.\ytmusic 7.29.52.apk' -d "Bypass certificate checks" -p .\patches-5.4.0.rvp`

Be sure to install Java Runtime Environment 11 beforehand. I used [OpenJDK v11.0.0.2 Install Page](https://jdk.java.net/java-se-ri/11-MR3) sourced from the [revanced-cli prerequisites page](https://github.com/ReVanced/revanced-cli/blob/main/docs/0_prerequisites.md). If you dont know how to install and set you env var, heres a [Youtube Video](https://www.youtube.com/watch?v=eHfmPnY8ewY)

thanks to those above for the help with the temporary fix.

**Comment by jirat-sumitanun** [comment]
I got this error.
command I used 

> java -jar .\revanced-cli-5.0.1-all.jar patch .\youtube.music_7.29.52.apk -d "Bypass certificate checks" -p .\patches-5.4.0.rvp

```
com.google.common.base.VerifyException
        at com.google.common.base.Verify.verify(Verify.java:102)
        at com.android.tools.build.apkzlib.zip.utils.MsDosDateTimeUtils.packDate(MsDosDateTimeUtils.java:84)
        at com.android.tools.build.apkzlib.zip.utils.MsDosDateTimeUtils.packCurrentDate(MsDosDateTimeUtils.java:103)
        at com.android.tools.build.apkzlib.zip.CentralDirectoryHeader.<init>(CentralDirectoryHeader.java:121)
        at com.android.tools.build.apkzlib.zip.ZFile.makeStoredEntry(ZFile.java:1788)
        at com.android.tools.build.apkzlib.zip.ZFile.add(ZFile.java:1747)
        at com.android.tools.build.apkzlib.zip.ZFile.add(ZFile.java:1711)
        at com.android.tools.build.apkzlib.zip.ZFile.add(ZFile.java:1691)
        at app.revanced.library.ApkUtils.applyTo(ApkUtils.kt:56)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:333)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

**Comment by jirat-sumitanun** [comment]
> [@jirat-sumitanun](https://github.com/jirat-sumitanun) you probably are using the built in java and not the required Zulu/openjdk Java. This issue is not for troubleshooting how to use cli. Use discord or Reddit if you need help patching.
> 
> [#5718 (comment)](https://github.com/ReVanced/revanced-patches/issues/5718#issuecomment-3234235820)

this is not the required openjdk?
```
java --version
openjdk 11.0.0.2 2024-07-02
OpenJDK Runtime Environment 18.9 (build 11.0.0.2+2-2)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.0.2+2-2, mixed mode)
```

**Comment by jpa102** [comment]
>Edit: Also tested v7.29.52 with the latest dev version of the patches v5.34.1-dev.3 and it gives the same 400 error.

it's indeed telling something that the old patches `5.4.0` version for yt music is way different than the latest `5.34.0` version (or the `v5.34.1-dev.3` version you stated)

no wonder why the version i suggested works (i didn't even bother updating my build back then because "it just works")

**Comment by planktonwhc** [comment]
java -jar revanced.jar patch -p patches-5.4.0.rvp yt.7.29.52.apk

using YTM-7.29.52.apk
5.4.0 patches
revanced cli
done and working

**Comment by Srinath10X** [comment]
revanced-cli-5.0.1 + YTM 7.29.52 + revanced-patches-5.4.0.rvp worked for me 🚀🚀🚀

**Comment by barbicane** [comment]
Patched with revanced cli ytm-7.29.52 patch 5.4.0 but music play is locked to first 60 seconds.

**Comment by kisnickla** [comment]
In my end the problem persists in the combination:

Revanced YTM (all versions+patches)  -  Primary google account (the one I used for years)

Secondary account works fine, also if i connect with my primary account in YTM with every other way except the android app (browser PC+Android) or through YMusic app (has a beta feature to use YTM from inside their app), works also fine.

**Comment by DREAMSOLDIERc404** [comment]
> java -jar revanced.jar patch -p patches-5.4.0.rvp yt.7.29.52.apk
> 
> using YTM-7.29.52.apk 5.4.0 patches revanced cli done and working

Worked!!!! Thankssss @jpa102!

**Comment by jpa102** [comment]
>Request contains an invalid argument

that's likely to be the cause of the http `400` status code, as the code references `Bad Request`

**Comment by Pustoy1243** [comment]
@rbnhd Good afternoon. I apologize, I have a request, could you please provide access to the apk file of the patched YouTube Music 7.29.52

**Comment by Pustoy1243** [comment]
@rbnhd Can you provide access to the patched YouTube Music 7.29.52?

**Comment by PowerWiesel** [comment]
> edit: seems that the "revanced cli ytm-7.29.52 patch 5.4.0" combination method works, but for some reason it took many minutes to apply the patch from the command line.

can confirm - also works for me.

I also got an even older working version. 7.03.52, but I cant tell you which patch I used back then. The only thing I can tell you is that I patched it on 24.08.2024.. so it's probably whatever was latest then.
It complains that it is outdated, but works fine. The older version was installed via rout mount, if that's important for whatever reason.

**Comment by jpa102** [comment]
>is that I patched it on 24.08.2024

@PowerWiesel based on that given date, this comes from the [`4.13.0` version of revanced patches](https://github.com/ReVanced/revanced-patches/releases/tag/v4.13.0)

>The older version was installed via root mount

looks like root installs and non-root installs are going to have different results, this needs more confirmation i guess (mine is non-root)

**Comment by rbnhd** [comment]
> [@rbnhd](https://github.com/rbnhd) Can you provide access to the patched YouTube Music 7.29.52?

@Pustoy1243 
Distributing patched apk goes against GitHub's policy. Or even if it didn't, I wouldn't do that. 
If you have a PC, u can do it very easily. Here are the steps. 

Download these:
- [revanced cli 5.0.1](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.1)
- [patches 5.4.0 rvp file](https://github.com/ReVanced/revanced-patches/releases/tag/v5.4.0)
- youtubemusic-7.29.52-arm64-v8a  exact version from apk mirror, or apk pure. 

Then run this command, make sure latest java is installed in ur PC. 
`java -jar revanced-cli-5.0.1.jar patch youtubemusic-7.29.52-arm64-v8a.apk -p patches-5.4.0.rvp`

**Comment by RileyXX** [comment]
I was able to get it working by patching with revanced extended manager using specific patch settings.

Revanced extended manager is a fork of the original revanced manager and can be installed alongside regular revanced manager.

See below:

Download and install revanced extended manager (https://github.com/inotia00/revanced-manager/releases/latest). Download YouTube music version 8.12.53 nodpi (apkmirror), in revanced extended manager select the downloaded youtube music apk from storage, in the list of patches under the fix playback patch click the gear icon next to it and disable spoof client and enable spoof video streams then tap save (make sure you tap save or it wont apply). Select rest of desired patches and install.

![Image](https://github.com/user-attachments/assets/6ac70a29-abb5-430c-a19b-7c5426a7ca8e)

**Comment by IGiveMemes** [comment]
> I was able to get it working by patching with revanced extended manager using specific patch settings.
> 
> Revanced extended manager is a fork of the original revanced manager and can be installed alongside regular revanced manager.
> 
> See below:
> 
> Download and install revanced extended manager (https://github.com/inotia00/revanced-manager/releases/latest). Download YouTube music version 8.12.53 nodpi (apkmirror), in revanced extended manager select the downloaded youtube music apk from storage, in the list of patches under the fix playback patch click the gear icon next to it and disable spoof client and enable spoof video streams then tap save (make sure you tap save or it wont apply). Select rest of desired patches and install.
> 
> ![Image](https://github.com/user-attachments/assets/6ac70a29-abb5-430c-a19b-7c5426a7ca8e)

Can confirm this works. Appreciate it! Tried the same with normal revanced, does not work.

**Comment by JoeGeeGameDev** [comment]
This above worked for me RVX Manager (not working with Normal Revance either)

**Comment by nevmiku** [comment]
RileyXX's method didn't work for me. Ran into the 60 second limit issue.
