### ISSUE TITLE
bug: YouTube 

### ISSUE THREAD

**Issue by killerlearner** [revanced/revanced-patches#599]
### Type

Other

### Bug description

After patching official YouTube v17.36.37 it's auto rotate in landscape without enabling auto rotate in system stopped working. In official apk it got auto rotate which side i choose without enabling auto rotate in system which i prefer but now need to enable auto rotate to rotate screen anti-clockwise in landscape. 
 +In patched verison at home screen of yt back button is not closing app. Which need to be fixed soon!

### Steps to reproduce

![Screenshot_2022-09-23-23-15-05-828_app revanced manager flutter](https://user-images.githubusercontent.com/67904798/192026599-d1bc6f0e-2fad-4520-8dfb-2550c6e6fc23.png)
Install this patches and you will see

### Relevant log output

```shell
No Log
```

### Additional context

If possible please back button issue first 😅

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by webzeroacs** [comment]
I think Remove general ads is the problem. If you change this part to general ads are shown, the back button will exit well.

**Comment by webzeroacs** [comment]
If you turn off Remove general ads, there will be Home ads and ads under the video. So I think there should be a bug fix for that part.

**Comment by killerlearner** [comment]
And screen rotation is still present issue which stop working after patching.

**Comment by oSumAtrIX** [comment]
It stops working on the YouTube app, not after patching.

**Comment by webzeroacs** [comment]
> It stops working on the YouTube app, not after patching.

 "It stops working on the YouTube app", a screen rotation problem?
Not the back button for exit, right?

**Comment by raniesantos** [comment]
@oSumAtrIX I browsed the pulls and commits, I didn't see anything indicating this was fixed.

Please explain why this is closed.

**Comment by oSumAtrIX** [comment]
@raniesantos https://github.com/revanced/revanced-patches/issues/599#issuecomment-1256933343

**Comment by killerlearner** [comment]
> It stops working on the YouTube app, not after patching.

But without patching i checked and it was working 🤔
 And yeah back button problem is linked with general ads.

**Comment by oSumAtrIX** [comment]
Without patching it still does not work, record and show that it works by logging into the unpatched client and restarting the app, then auto-rotating regardless of having auto-rotate setting disabled.

**Comment by raniesantos** [comment]
Ok, I did a bit more digging.

https://redd.it/x686m0

**Comment by killerlearner** [comment]
> Ok, I did a bit more digging.
> 
> https://redd.it/x686m0

Yeah after i install YouTube i checked rotation is was working. Ig cuz it was cleared cache and all
So any hope for fixing it in patches also and also back button issue without disabling general ads will be great too.

**Comment by oSumAtrIX** [comment]
Swipe up instead of back, minor inconvenience which won't be fixed until swipe down gesture is fixed.

**Comment by killerlearner** [comment]
So just in case keep this issue open so people don't create duplicate and keep it in mind to fix. 
And auto rotation issue is also in this.
