### ISSUE TITLE
feat(YouTube): Hide trending results during video search (non-litho how-to)

### ISSUE THREAD

**Issue by 0xrxL** [ReVanced/revanced-patches#873]
### Application

YouTube

### Issue

UPDATE: Based on a recent feedback from @Aryan-Chauhan, the app now show two distinct type of trending results (with and without fire icon): 
![331839904-61ea83a4-253d-4e37-8dd0-50d5ab664e0f](https://github.com/ReVanced/revanced-patches/assets/127248639/ac1f8dff-bd38-4fd7-9aaa-3a51f0c2f4c9)

Starting with the latest 18.1x versions, Google has introduced trending searches when searching for videos, as you can see in the screenshot below:

<img width="176" alt="4" src="https://github.com/revanced/revanced-patches/assets/127248639/f9ad2a84-8c2f-4663-aae5-e699da2c2f54">

### Patch

- Create a method to hide/show the parent of a view, as shown in the following screenshot:
<img width="538" alt="3" src="https://github.com/revanced/revanced-patches/assets/127248639/53d09a51-f8d4-46d7-a859-e95d6e9ef5e1">

- Pass the imageview of resource "R.drawable.yt_outline_fire_black_24" as parameters for the method "SearchSuggestionVisibility(imageView, boolean)", with parameter boolean set to "false", as shown in the following screenshot:
<img width="651" alt="1" src="https://github.com/revanced/revanced-patches/assets/127248639/921be701-4fe0-4a52-bb4e-68979a935a41">

- Pass the imageview of resource "R.drawable.yt_outline_arrow_time_black_24" and "R.drawable.yt_outline_search_black_24" as parameters for the method "SearchSuggestionVisibility(imageView, boolean)", with parameter boolean set to "true", as shown in the following screenshot:
<img width="638" alt="2" src="https://github.com/revanced/revanced-patches/assets/127248639/5d894873-b7ca-4695-90dc-6dd6cf8bdc23">

### Motivation

Remove useless and annoying searching results.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Aryan-Chauhan** [comment]
I think it is now globally enabled for all users. Now there are 2 types of trending searches.

BTW, my search history is disabled & has zero items in it. Also, watch history is disabled & has zero items in it.

@0xrxL Can you edit your issue and include the below screenshot & mention that there are now 2 types of trending searches `fire & non-fire` ?

**Comment by 0xrxL** [comment]
Done

**Comment by 0xrxL** [comment]
@LisoUseInAIKyrios Do you need of a new issue with steps to implement this feature, based on last 19.16.39 version?

**Comment by 0xrxL** [comment]
I can't see these results anymore.

Tested it on 3 accounts.

**Comment by Aryan-Chauhan** [comment]
Kindly re-open. I'm still getting them on both dev & stable patches with recommended version of APK (clean installation everytime).

![Screenshot_2024-10-28-08-36-11-53_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/b02f3c4a-dbd5-436f-bc8a-0d7a9c2436a3)

**Comment by ILoveOpenSourceApplications** [comment]
This issue is still valid and should be reopened.

**Comment by 0xrxL** [comment]
I think it's not valid anymore, due to the last layout change.

**Comment by giwrgosmant** [comment]
> I think it's not valid anymore, due to the last layout change:
> 
> https://github.com/ReVanced/revanced-patches/issues/4101

These trending results still appearing for me.
![Screenshot_2025-01-22-12-11-30-88_64ef5fc2000c1caa954c114bb372e1d5.jpg](https://github.com/user-attachments/assets/283beddd-a590-46d7-9239-9d1f6e0197bf)

**Comment by ILoveOpenSourceApplications** [comment]
I didn't see the other issue, but yeah this can be closed as a follow-up to #4101.
